### ISSUE TITLE
api: shrink api to useful subset (was: api: move helper/convenience APIs to dedicated project)

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#128]
Several APIs are not directly related to the LaxarJS core functionality. 
They should be moved to a dedicated API package.

move:
* `utilities/array` _(remove)_
* `utilities/string`
* `utilities/fn`
* `logging`
* partial: `utilities/object` (_remaining:_ setPath, getPath, deepClone, deepFreeze, options)
* `i18n`

keep:
* `utilities/storage` (needed by timer, ThemeManager)

ensure private:
* `profiling` (make inclusion optional)
* `utilities/timer`
* `utilities/path`

Where applicable (logging), services/mocking should be provided by laxar_api for the included libraries.

**Comment by alex3683** [comment]
Instead of moving the api into a separate package, we will clean it up and remove the following apis:
- `array` completely
- `object.map`
- `string.endsWith`
- `string.capitalize`
- `string.upperCaseFromCamelCase`
- `string.removeUnderScoreFromCamelCase`

`LogContext` will be removed from the `logging` library.

**Comment by alex3683** [comment]
Implemented on `master` (`v1.0.0`).

### Breaking Change

The following general-purpose APIs have been removed from LaxarJS without replacement:

- `laxar.array` (removed completely)
- `laxar.object.map`
- `laxar.string.endsWith`
- `laxar.string.capitalize`
- `laxar.string.upperCaseFromCamelCase`
- `laxar.string.removeUnderScoreFromCamelCase`

Users should either re-implement these simple functions or migrate to a general-purpose library (such as underscore). Also removed:

- `laxar.log.context`
- `laxar.log.develop`, `laxar.log.data`, `laxar.log.account`, `laxar.log.statistics`, `laxar.log.audit`

The methods `addTag`, `setTag` and `gatherTags` from `laxar.log.context` have been moved to `laxar.log`. The _Application Instance ID_ (used to identify log messages for the same client session) is no longer generated on logger initialization, but instead by `laxar.bootstrap`.

Instead of the removed log-levels `DEVELOP`, `DATA`, `ACCOUNT`, `STATISTICS` and `AUDIT`, user-defined log-levels are now supported through configuration. To use them, the configuration key `logging.levels` must be set to an object, mapping level names to their numeric severity values (the higher the more severe). These are the  built-in levels with severity:

- `TRACE`: 100
- `DEBUG`: 200
- `INFO`: 300
- `WARN`: 400
- `ERROR`: 500
- `FATAL`: 600

General-purpose widgets should avoid using non-standard log-levels, but if they do they need to document any non-standard levels they require.
