### ISSUE TITLE
integration: provide bundled & minified "laxar.js" file

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/laxar#133]
It would be really nice if we had a one-file-solution to ship LaxarJS. Ideally, this file should be usable without any [special](http://requirejs.org/docs/api.html#packages) RequireJS configuration. (This probably requires a little bit of research to get working, because we use RequireJS internally and rely on it being configured in a specific way.)

Requirements:
- [x] a single `laxar.js` file
- [x] a minified `laxar.min.js` file
- [x] sourcemaps in `laxar.min.js.map`
- [x] make it work without a RequireJS "package" configuration

**Comment by x1B** [comment]
Because we do not want to manage source- and build-artifacts in the same repository, let's take a different approach entirely, which is more along the lines of what the AngularJS project does.

There will be new repositories for the distribution-ready LaxarJS libraries:
* `dist-laxar`
* `dist-laxar-patterns`
* `dist-laxar-uikit`

Each of these repositories will provide both a concatenated and a minified build of the respective LaxarJS artifact, for use with the bower-registry. For LaxarJS 1.0, we plan to update the repository naming of laxar_uikit and laxar_patterns to laxar-uikit and laxar-patterns respectively; so these names would match.

For LaxarJS-core, there is an additional "full" version that contains all dependencies (AngularJS, angular-route, jjv etc.). This would be the version that requires the least amount of RequireJS-configuration and uses the smallest number of HTTP-requests during development.

**Comment by x1B** [comment]
Additionally, the _dist_ artifacts should contain all _generated_ (API) doc.

**Comment by x1B** [comment]
### Usage Information

A LaxarJS _bower package_ is now available:

```sh
bower install laxarjs
```
