### ISSUE TITLE
The LaxarJS runtime cannot find the main default.theme (was: The debug.html doesn't find the fallback theme)

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/laxar#236]

**Comment by jonaswjs** [comment]
laxar.js Line 4766 (urlProvider): change artifactPathPattern to pattern

**Comment by x1B** [comment]
@jonaswjs I modified the title because the debug.html is not part of this repository.
The file `laxar.js` is from `dist-laxar` (and the line is valid for `v1.1.0-alpha.7`).
To fix this, you'll need to modify the [ThemeManager](//github.com/LaxarJS/laxar/blob/master/lib/runtime/theme_manager.js#L87).

**Comment by x1B** [comment]
Fixed on `master` (`v1.1.0`).
