### ISSUE TITLE
Evaluate webpack as yet another alternative to RequireJS (and JSPM with SystemJS)

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar#298]
First steps with JSPM / SystemJS and a very small project already show severe performance problems. Causes are the many small files loaded into the browser and the on-the-fly babel compilation. So the next popular alternative seems to be webpack (in fact many former JSPM users switched there, see here for example: http://blog.dripstat.com/why-we-switched-from-jspm-to-webpack/).

**Comment by alex3683** [comment]
Current work in progress is tracked at branch feature/298-build-laxar-using-webpack

**Comment by x1B** [comment]
@alex3683 thanks for the proof-of-concept, I'll assign to me for now

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).

### BREAKING CHANGE

The LaxarJS core library is now bundled using webpack. Because the library is bundled as a UMD-module, projects should still be able to load the bundled version using RequireJS, or even to load the source version dynamically through JSPM.
When projects use webpack for module loading as well, this dramatically improves page load speed during development (most obviously compared to JSPM, but also compared to RequireJS if the webpack-dev-server is used to serve modules).

However, because webpack does not currently support dynamic loading and path resolution, loading of widgets and controls through `amd:` references at runtime does no longer work. This will be addressed by pre-computing all references to widgets and controls at project build time.

Also, the way that the core tests are run in the browser has changed: the HTML spec runners are now generated.

Run `npm run browser-spec` and point your browser to `http://localhost:8201/spec-output` to access the generated spec runners.
