### ISSUE TITLE
event bus: remove mediator API and setErrorHandler

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#308]
The mediator API has not really been used at all, so it should be removed.

Instead we *may* want to allow to decorate all (public) services by providing hooks during bootrapping, which would be very useful for testing, and would indirectly allow to modify the event bus behavior.

**Comment by alex3683** [comment]
Additionally we can now safely remove `setErrorHandler`, as we now only support the laxar log for event bus error handling.

**Comment by alex3683** [comment]
Implemented on `master` (`v2.0.0`).

### Breaking Change

The mediator api and the possibility to set a custom error handler for the event bus were completely removed. These two apis stem from times where we thought about publishing the event bus as separate repository for use by other frameworks or libraries. Since this never happened and won't be the case in near future, we can safely get rid of such overhead. We never used them ourselves.
