### ISSUE TITLE
Make purpose of "onBeforeControllerCreation" clearer

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar#413]
Adapters receive a callback called `onBeforeControllerCreation`. They should call this function whenever a widget controller is instantiated with the map of services that were passed to that controller.
Used is this information only by laxar-mocks to make these services available to widget tests. Here the function is implemented and also called `onBeforeControllerCreation`.

In both cases the naming is somewhat misleading. For adapters the name should be more imperative (e.g. `provideServices`) and in the case of laxar-mocks the function should clearer state its purpose (e.g. `whenServicesAreAvailable`).

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0-alpha.14`).

### BREAKING CHANGE

The widget adapter environment has been changed. The method `onBeforeControllerCreation` has been renamed to `provideServices`. Widget adapters must call this method in order to inform tooling (such as [laxar-mocks](//github.com/LaxarJS/laxar-mocks)) about the actual set of widget injections.

The method `widgetLoader.load` has been modified accordingly: The callback option `onBeforeControllerCreation` was renamed to `whenServicesAvailable` to clarify its purpose.
