### ISSUE TITLE
question: LaxarJS in nw.js Application

### ISSUE THREAD

**Issue by n3utrino** [LaxarJS/laxar#421]
I have a somewhat unusual usecase and i am wondering if LaxarJS could be the glue for my solution.

I am integrating two webapplications in one nw.js application. Those two applications should be able to communicate with each other. So I am doing this at the moment by loading both applications in a web-view in nw.js an injecting the communication javascript code to use the post message API.

The communication between the applications is limited to:
- Navigation
- Availability

I imagine the nw.js application would consist of one page with each of the two webapps being one widget. So I could use the LaxarJS event bus as the glue between the two.

My questions are:
Is LaxarJS able to run in a nw.js environment?
How would I ideally set up this environment?

**Comment by x1B** [comment]
Hey @n3utrino, thanks for getting in touch.

Interesting question... so far, we haven't had any experience with nw.js or interfacing LaxarJS with it.

In principle, this should work since LaxarJS is webkit-compatible after all. I'd imagine the first step to test this would be to create a project using the generator (as described in the [getting started docs](http://laxarjs.org/docs/laxar-latest/#getting-started)), and trying to load that into a web view.

Your approach in using two widgets for your content applications seems reasonable.

I am not sure though, if you can get away without using postMessage: If the CSS of the two applications is compatible (ideally, if both are Bootstrap3-based) and if the applications themselves are well-behaved (not polluting the JS global scope too much etc.), you might be able to load them directly with LaxarJS and have them interact through the event bus.

Please note that so far LaxarJS is biased towards AngularJS 1.x and AMD/RequireJS, and has a direct dependency to those. So if both your content applications are written using AngularJS (1.x) with AMD modules, they'd probably be much simpler to integrate than if they are written in, say, Backbone with CommonJS.

This will change with 2.0 (coming this year, hopefully sometime in spring), which integrates all MVC technologies through plugins, and uses webpack2-based builds. For v1.x there already is an adapter for [react](http://laxarjs.org/docs/laxar-react-adapter-latest/) as well as a builtin adapter for [plain old JavaScript integration](https://laxarjs.org/docs/laxar-latest/manuals/writing_widget_controllers/) which should be versatile, but both are somewhat second-class citizens until 2.0 is released.

Looking forward to hearing more about your project! If you'd like to discuss details, you can also get in touch with me through x1b at laxarjs.org.

**Comment by n3utrino** [comment]
Hi @x1B, thanks for the in depth reply.

I am going to try the plain old JavaScript integration.

My setup is somewhat complex consisting of 
* Application 1 served from https://server1 written with jquery and from external vendor with minimal possibilities to customize, not being a single page app and not well behaved at all (framebuster code, thats why a web-view is needed).
* Application 2 written in house in typescript / angular1 served from https://server2
* nwjs Client to integrate the two installed on the users machine where a index.html with two web-views consisting of App1 and App1 are loaded. Nwjs acting as host and injecting the gluecode in the two applications.

You are right as long as the two applications are served from their own servers I must use postMessage to communicate on the client side.
It looks like I would need to write a postMessage proxy for the LaxarJS features I want to use.

I'll gladly take the offer to contact you, once I have some more insight, and can ask the "not anymore so stupid questions" ;-)

**Comment by x1B** [comment]
Hi @n3utrino, thanks for sharing these details.

We've actually encountered similar integration scenarios where we need to interact with iframes. So there's probably a good use case for an additional "iframe" integration technology to transparently bridge externally hosted application parts into a LaxarJS project.

Best of luck and looking forward to more questions! :)

(closing this issue for now, feel free to keep commenting or opening new issues)
