### ISSUE TITLE
axFlowService: hashbang navigation breaks if path is `/`

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#430]
When using hashbang-navigation with the minimal path `/` (for example using the URL `http://localhost/#!/browse` as opposed to `http://localhost/index.html#!/browse`), the routing fragment gets rewritten to `#!browse`, and navigation gets redirected to the place `error404`.

Not sure if this is an issue with page.js or with our URL handling.

**Comment by alex3683** [comment]
This issue is triggered within page.js in the `Context` constructor function.

The path for the context to create is tested if it is already prefixed with the base url (in the case of our testing project this is`/`). In case it is not, the prefix is added, including the hashbang part. Later, the base is removed again to have the path.

With `/` as base, page.js thinks the path (in our case `/browse` is already prefixed with the base and thus later removes it, which creates the invalid fragment and breaks routing.

**Comment by alex3683** [comment]
Fixed on `master` (`v2.0.0`).
