### ISSUE TITLE
footprint: use webpack3 with scope-hoisting

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#470]
To reduce bundle size, we'd like to use the new ScopeHoistingPlugin provided by webpack 3.

**Comment by jpommerening** [comment]
Seems to be working without any issues! ✨

Since we ship LaxarJS bundled but not minified, we get a bundle that is 289kB instead of 303kB (both with webpack 3). If we were to minify the bundle we would have 57.5kB instead of 59.2kB.
For reference: webpack 2 gives us 306kB (59.7kB minified).

For now, let's keep the configuration for this in the respective repositories, as doing so in `laxar-infrastructure` would either be a breaking change (requiring webpack 3) or we'd have to check dynamically if the plugin is available.

**Comment by jpommerening** [comment]
👌

implemented on `master`
